### ISSUE TITLE
create preloader for webapp beta

### ISSUE THREAD

**Issue by 2075** [nupic-community/nostradamIQ#50]
some slower machines/connections usually assume, the app either crashed or doesnt load, css preloader gives the user some feedback and will make him wait with pleasure :D

**Comment by passiweinberger** [comment]
Related to #53

**Comment by passiweinberger** [comment]
@2075 Feedback Welcome:

nostradamiq.org/webapp/preloader Here it is always shown // just cuz it's beautiful :P
