### ISSUE TITLE
show popover to explain basic navigation

### ISSUE THREAD

**Issue by 2075** [nupic-community/nostradamIQ#52]
like:

Hey there! Welcome to nostradamIQ. To give you an easy experience, here are some basic tips:
- click and drag to change lat/lon of view
- use scrollbar to zoom in and out
- choose a demo project from the top right to get started with some amazing data or
- create your own view with the datascources on the lower right

If you have questions: send us a message!

**Comment by passiweinberger** [comment]
Done :+1:
