### ISSUE TITLE
earthquake: loading time

### ISSUE THREAD

**Issue by 2075** [nupic-community/nostradamIQ#57]
is it possible to show items during loading or do you need to parse the complete dataset first?

if possible, show  preloader and maybe show items as soon as they are parsed.
location names are not necessary for understanding the stations, therefore maybe show them on rollover and find an icon (check linearicons icons, clean look, or fontawesome or glyphicons) to show instead of black square

**Comment by passiweinberger** [comment]
we need all of them. plotting a LAYER takes most time in the process, so if you were to mark the points individually and the plot each point at a time the entire process would be much longer...

**Comment by passiweinberger** [comment]
Closed with #53

**Comment by 2075** [comment]
the user needs feedback and does not care so much about how much time you need to plot something.

**Comment by passiweinberger** [comment]
Makes Sense, I'll cover that with a general loading did that pops up whenever we load something:)
