### ISSUE TITLE
create possibility to deeplink to preset views

### ISSUE THREAD

**Issue by 2075** [nupic-community/nostradamIQ#60]
for example for promotion you will be able to send a direct link to the internet or seismic data demo.

**Comment by passiweinberger** [comment]
@2075 Do you mean this: https://nostradamiq.org/webapp/index.html?layersOn=usgs-all-7day,seismic_stations&baseLayer=0&viewerMode=3D  ?

**Comment by passiweinberger** [comment]
Assume that is what you meant :)
